/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class peter_instrument_MySHStub */

#ifndef _Included_peter_instrument_MySHStub
#define _Included_peter_instrument_MySHStub
#ifdef __cplusplus
extern "C" {
#endif

#include <stdio.h>
#include <sys/types.h>
#include <sys/ipc.h>
#include <sys/shm.h>

#define SHMSZ 100

/*
 * Class:     peter_instrument_MySHStub
 * Method:    getSharedMemory
 * Signature: ()Ljava/lang/String;
 */

int x;
key_t key;

JNIEXPORT jstring JNICALL Java_peter_instrument_MySHStub_getSharedMemory(JNIEnv * env, jobject object) {
	int shmid;

	char *shm;
	//	printf("sss\n");
	char *s = malloc(100);

//	printf("key=%x\n", key);
//	printf("shmid=%x\n", shmid);
//	printf("shm=%x\n", shm);
//	if (key == 0) {
		key = 0x2241980;
		if ((shmid = shmget(key, SHMSZ, 0666)) < 0) {
			perror("shmget");
			return NULL;
		}

		if ((shm = shmat(shmid, NULL, 0)) == (char *) -1) {
			printf("shmat error\n");
			return NULL;
		}
//	}

	//	printf("waiting\n");
	//	printf("shm=%s\n", shm);
	while (*shm == 'S')
		;

	//	printf("ok now\n");
	//	fflush(stdout);
	//	*shm = 'P';

	//	printf("start\n");
	//	fflush(stdout);
	char *temp = shm + 1;
	char *s2 = s;
	while (*temp != '\0') {
		*s++ = *temp++;
	}
	*s = '\0';

	//	printf("s=%s\n", s);
	//	fflush(stdout);
	*shm = 'S';

	//	if (s != NULL) {
	//		char * str;
	//		str = (char*) (*env)->GetStringUTFChars(env, string1, NULL);
	//		printf("%s", str);
	//		strcpy(str, "fuck");
	//		(*env)->ReleaseStringUTFChars(env, s, str);
	//	}
//	printf("temp=%s\n", s2);
//	fflush(stdout);
	jstring rtstr = (*env)->NewStringUTF(env, s2);

	shmdt(shm);
	//	printf("end shm=%s\n", shm);
	//	fflush(stdout);
	return rtstr;
}

#ifdef __cplusplus
}
#endif
#endif
