/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class peter_instrument_MySHStub */

#ifndef _Included_peter_instrument_MySHStub
#define _Included_peter_instrument_MySHStub
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     peter_instrument_MySHStub
 * Method:    getSharedMemory
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_peter_instrument_MySHStub_getSharedMemory
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
